Курсовая ASP.NET/Курсовая ASP.NET/Controllers/ResidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Курсовая_ASP.NET;

namespace Курсовая_ASP.NET.Controllers
{
    public class ResidentsController : Controller
    {
        private HostelEntities db = new HostelEntities();

        // GET: Residents
        public ActionResult Index(bool IsShowEvicted = false)
        {
            var residents = db.Residents.Include(r => r.Cities).Include(r => r.Rooms);
            ViewBag.Residents = residents.ToList();
            ViewBag.IsShowEvicted = IsShowEvicted;
            return View(ViewBag);
        }
        // GET: Residents/Create
        public ActionResult Create()
        {
            ViewBag.IdCity = new SelectList(db.Cities, "Id", "City");
            ViewBag.IdRoom = new SelectList(db.Rooms, "Id", "Number");
            return View();
        }

        // POST: Residents/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Passport,Name,Patronymic,Surname,IdCity,SettlementDate,IdRoom,IsEvicted")] Residents residents)
        {
            if (string.IsNullOrEmpty(residents.Passport) || residents.Passport.Length != 10)
            {
                ModelState.AddModelError("Patronymic", "Некорректный паспорт");
            }
            if (string.IsNullOrEmpty(residents.Name))
            {
                ModelState.AddModelError("Name", "Некорректное имя");
            }
            if (string.IsNullOrEmpty(residents.Patronymic))
            {
                ModelState.AddModelError("Patronymic", "Некорректное отчество");
            }
            if (string.IsNullOrEmpty(residents.Surname))
            {
                ModelState.AddModelError("Surname", "Некорректное фамилия");
            }

            Rooms room = db.Rooms.Find(residents.IdRoom);
            if (room?.FreePlace == 0)
            {
                ModelState.AddModelError("IdRoom", "В номере нет свободных мест");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    db.Residents.Add(residents);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    return View("Error");
                }

                return RedirectToAction("Index");
            }

            ViewBag.IdCity = new SelectList(db.Cities, "Id", "City", residents.IdCity);
            ViewBag.IdRoom = new SelectList(db.Rooms, "Id", "Number", residents.IdRoom);
            return View(residents);
        }

        // GET: Residents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Residents residents = db.Residents.Find(id);
            if (residents == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdCity = new SelectList(db.Cities, "Id", "City", residents.IdCity);
            ViewBag.IdRoom = new SelectList(db.Rooms, "Id", "Number", residents.IdRoom);
            return View(residents);
        }

        // POST: Residents/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Passport,Name,Patronymic,Surname,IdCity,SettlementDate,IdRoom,IsEvicted")] Residents residents)
        {
            if (string.IsNullOrEmpty(residents.Passport) || residents.Passport.Length != 10)
            {
                ModelState.AddModelError("Patronymic", "Некорректный паспорт");
            }
            if (string.IsNullOrEmpty(residents.Name))
            {
                ModelState.AddModelError("Name", "Некорректное имя");
            }
            if (string.IsNullOrEmpty(residents.Patronymic))
            {
                ModelState.AddModelError("Patronymic", "Некорректное отчество");
            }
            if (string.IsNullOrEmpty(residents.Surname))
            {
                ModelState.AddModelError("Surname", "Некорректное фамилия");
            }

            Rooms room = db.Rooms.Find(residents.IdRoom);
            if (room?.FreePlace == 0)
            {
                ModelState.AddModelError("IdRoom", "В номере нет свободных мест");
            }
            if (ModelState.IsValid)
            {
                db.Entry(residents).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdCity = new SelectList(db.Cities, "Id", "City", residents.IdCity);
            ViewBag.IdRoom = new SelectList(db.Rooms, "Id", "Number", residents.IdRoom);
            return View(residents);
        }

        // GET: Residents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Residents residents = db.Residents.Find(id);
            if (residents == null)
            {
                return HttpNotFound();
            }
            return View(residents);
        }

        // POST: Residents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "DepartureDate")]int id, DateTime? departureDate)
        {
            Residents residents = db.Residents.Find(id);
            if (departureDate == null)
            {
                ModelState.AddModelError("DepartureDate", "Нужно указать дату выселения");
            }
            else if (departureDate < residents.SettlementDate)
            {
                ModelState.AddModelError("DepartureDate", "Дата выселения не может быть раньше даты заселения");
            }
            if (!ModelState.IsValid)
            {
                return View(residents);
            }
            residents.IsEvicted = true;
            Accommodation accommodation = db.Accommodation.FirstOrDefault(ac =>
                ac.IdRoom == residents.IdRoom && ac.SettlementDate == residents.SettlementDate &&
                ac.DepartureDate == null);
            accommodation.DepartureDate = departureDate;
            Rooms rooms = db.Rooms.Find(residents.IdRoom);
            rooms.FreePlace++;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Курсовая ASP.NET/Курсовая ASP.NET/Views/Residents/Create.cshtml
@model Курсовая_ASP.NET.Residents

@{
    ViewBag.Title = "Заселить";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Паспорт", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Passport, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Passport)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Имя", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Отчество", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Фамилия", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Surname)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Город", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DropDownList("IdCity", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCity)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Дата заселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                <input type="date" class = "form-control" id="SettlementDate" name="SettlementDate" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Номер", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DropDownList("IdRoom", null, htmlAttributes: new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.IdRoom)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <input type="submit" value="Заселить" class="btn btn-default" />
                @Html.ActionLink("Назад", "Index")
            </div>
        </div>
    </div>
}

Курсовая ASP.NET/Курсовая ASP.NET/Views/Residents/Delete.cshtml
@model Курсовая_ASP.NET.Residents

@{
    ViewBag.Title = "Выселить";
}

<h3>Вы уверены что хотите выселить @Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.Patronymic) @Html.DisplayFor(model => model.Surname) ?</h3>
<div>
    <hr />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            @Html.Label("Дата выселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                <input type="date" class="form-control" id="DepartureDate" name="DepartureDate" />
                @Html.ValidationMessage("DepartureDate");
            </div>
        </div>

            <div class="form-actions no-color">
                <input type="submit" value="Выселить" class="btn btn-default" /> |
                @Html.ActionLink("Назад", "Index")
            </div>
            }
        </div>

Курсовая ASP.NET/Курсовая ASP.NET/Views/Residents/Edit.cshtml
@model Курсовая_ASP.NET.Residents

@{
    ViewBag.Title = "Изменить";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.IsEvicted)
    @Html.HiddenFor(model => model.SettlementDate)

    <div class="form-group">
        @Html.Label("Паспорт", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Passport, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Passport)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Имя", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Отчество", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Patronymic)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Фамилия", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Surname)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Город", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.DropDownList("IdCity", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdCity)
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Номер", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-2">
            @Html.DropDownList("IdRoom", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdRoom)
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <input type="submit" value="Сохранить" class="btn btn-default" />
            @Html.ActionLink("Назад", "Index")
        </div>
    </div>
</div>
}

Курсовая ASP.NET/Курсовая ASP.NET/Views/Residents/Index.cshtml
@using System.Web.UI.HtmlControls
@{
    ViewBag.Title = "Клиенты";
}

<p class="btn btn-default">
    @Html.ActionLink("Заселить", "Create")
</p>
<table id="idResident" class="table form-group">
    <thead>
        <tr>
            <th>Паспорт</th>
            <th>Клиент</th>
            <th>Дата заселения</th>
            <th>Город</th>
            <th>Номер</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Residents item in ViewBag.Residents)
        {
            if (ViewBag.IsShowEvicted || !item.IsEvicted)
            {
                string color = "black";
                if (item.IsEvicted)
                {
                    color = "red";
                }

                <tr style="color: @color">
                    <td>@Html.DisplayFor(modelItem => item.Passport)</td>
                    <td>@Html.DisplayFor(modelItem => item.Name) @Html.DisplayFor(modelItem => item.Patronymic) @Html.DisplayFor(modelItem => item.Surname)</td>
                    <td>@Html.DisplayFor(modelItem => item.SettlementDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.Cities.City)</td>
                    <td>@Html.DisplayFor(modelItem => item.Rooms.Number)</td>
                    @if (!item.IsEvicted)
                    {
                        <td style="color: black">
                            @Html.ActionLink("Изменить", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Выселить", "Delete", new { id = item.Id })
                        </td>
                    }
                </tr>
            }
        }
    </tbody>

</table>

<input type="checkbox" checked="@ViewBag.IsShowEvicted" class="form-group" id="chk" />
<label for="chk">Показать выcеленных клиентов </label>

<script type="text/javascript">
    $(document).ready(function() {
        $('#chk').change(function(e) {
            var theUrl;
            if (e.target.checked) {
                theUrl = '@Url.Action("Index", "Residents", new {IsShowEvicted = true}, null)';
            } else {
                theUrl = '@Url.Action("Index", "Residents", new {IsShowEvicted = false}, null)';
                }
            window.location = theUrl;
        });
    });
</script>